"""Add original and sanitized text to ai_audits

Revision ID: 05607d0df446
Revises: 6e820bd17449
Create Date: 2026-09-24 12:01:53.695146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05607d0df446'
down_revision: Union[str, Sequence[str], None] = '6e820bd17449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_audits', sa.Column('original_text', sa.Text(), nullable=False))
    op.add_column('ai_audits', sa.Column('sanitized_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_audits', 'sanitized_text')
    op.drop_column('ai_audits', 'original_text')
    # ### end Alembic commands ###
